# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.MixProject do
  use Mix.Project

  @version "0.1.0"

  def project do
    [
      app: :googly_cloud_storage,
      version: @version,
      elixir: "~> 1.18",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      description:
        "Google Cloud Storage JSON API client library. Stores and retrieves potentially large, immutable data objects.",
      package: package(),
      docs: [main: "readme", extras: ["README.md"]],
      source_url: "https://github.com/Rabbet/googly/tree/main/clients/googly_cloud_storage"
    ]
  end

  def application do
    [extra_applications: [:logger]]
  end

  defp deps do
    [
      {:req, "~> 0.6"},
      {:jason, "~> 1.4"},
      {:ex_doc, "~> 0.40", only: :dev, runtime: false}
    ]
  end

  defp package do
    [
      licenses: ["Apache-2.0"],
      files: ~w(lib mix.exs README.md LICENSE .formatter.exs),
      links: %{
        "GitHub" => "https://github.com/Rabbet/googly/tree/main/clients/googly_cloud_storage",
        "Google API docs" => "https://developers.google.com/storage/docs/json_api/"
      }
    ]
  end
end
