# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Projects.Locations.Processors.HumanReviewConfig do
  @moduledoc """
  Endpoints for the `Projects.Locations.Processors.HumanReviewConfig` resource.
  """

  alias Googly.DocumentAI.Request

  @doc """
  Send a document for Human Review. The input document should be processed by the specified processor.

  ## Parameters

  *   `human_review_config` (*type:* `String.t()`) - Required. The resource name of the HumanReviewConfig that the document will be reviewed with.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.
      *   `body` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ReviewDocumentRequest.t()`) - 

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleLongrunningOperation{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec review_document(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleLongrunningOperation.t()} | {:error, term()}
  def review_document(human_review_config, opts \\ []) do
    Request.run(
      method: :post,
      url: "/v1/{+humanReviewConfig}:reviewDocument",
      path_params: %{
        "humanReviewConfig" =>
          URI.encode(human_review_config, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"},
        body: {:body, nil}
      },
      decode: Googly.DocumentAI.Model.GoogleLongrunningOperation,
      opts: opts
    )
  end
end
