# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Projects.HmacKeys do
  @moduledoc """
  Endpoints for the `Projects.HmacKeys` resource.
  """

  alias Googly.CloudStorage.Request

  @doc """
  Creates a new HMAC key for the specified service account.

  ## Parameters

  *   `project_id` (*type:* `String.t()`) - Project ID owning the service account.
  *   `service_account_email` (*type:* `String.t()`) - Email address of the service account.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.HmacKey{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec create(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.HmacKey.t()} | {:error, term()}
  def create(project_id, service_account_email, opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/projects/{projectId}/hmacKeys",
      path_params: %{"projectId" => URI.encode(project_id, &URI.char_unreserved?/1)},
      query: [{"serviceAccountEmail", service_account_email}],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.HmacKey,
      opts: opts
    )
  end

  @doc """
  Deletes an HMAC key.

  ## Parameters

  *   `project_id` (*type:* `String.t()`) - Project ID owning the requested key
  *   `access_id` (*type:* `String.t()`) - Name of the HMAC key to be deleted.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request.

  ## Returns

  *   `{:ok, Req.Response.t()}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec delete(String.t(), String.t(), keyword()) :: {:ok, Req.Response.t()} | {:error, term()}
  def delete(project_id, access_id, opts \\ []) do
    Request.run(
      method: :delete,
      url: "/storage/v1/projects/{projectId}/hmacKeys/{accessId}",
      path_params: %{
        "projectId" => URI.encode(project_id, &URI.char_unreserved?/1),
        "accessId" => URI.encode(access_id, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"}
      },
      decode: nil,
      opts: opts
    )
  end

  @doc """
  Retrieves an HMAC key's metadata

  ## Parameters

  *   `project_id` (*type:* `String.t()`) - Project ID owning the service account of the requested key.
  *   `access_id` (*type:* `String.t()`) - Name of the HMAC key.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.HmacKeyMetadata{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec get(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.HmacKeyMetadata.t()} | {:error, term()}
  def get(project_id, access_id, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/projects/{projectId}/hmacKeys/{accessId}",
      path_params: %{
        "projectId" => URI.encode(project_id, &URI.char_unreserved?/1),
        "accessId" => URI.encode(access_id, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.HmacKeyMetadata,
      opts: opts
    )
  end

  @doc """
  Retrieves a list of HMAC keys matching the criteria.

  ## Parameters

  *   `project_id` (*type:* `String.t()`) - Name of the project in which to look for HMAC keys.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `max_results` (*type:* `integer()`) - Maximum number of items to return in a single page of responses. The service uses this parameter or 250 items, whichever is smaller. The max number of items per page will also be limited by the number of distinct service accounts in the response. If the number of service accounts in a single response is too high, the page will truncated and a next page token will be returned.
      *   `page_token` (*type:* `String.t()`) - A previously-returned page token representing part of the larger set of results to view.
      *   `service_account_email` (*type:* `String.t()`) - If present, only keys for the given service account are returned.
      *   `show_deleted_keys` (*type:* `boolean()`) - Whether or not to show keys in the DELETED state.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.HmacKeysMetadata{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec list(String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.HmacKeysMetadata.t()} | {:error, term()}
  def list(project_id, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/projects/{projectId}/hmacKeys",
      path_params: %{"projectId" => URI.encode(project_id, &URI.char_unreserved?/1)},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        max_results: {:query, "maxResults"},
        page_token: {:query, "pageToken"},
        service_account_email: {:query, "serviceAccountEmail"},
        show_deleted_keys: {:query, "showDeletedKeys"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.HmacKeysMetadata,
      opts: opts
    )
  end

  @doc """
  Updates the state of an HMAC key. See the [HMAC Key resource descriptor](https://cloud.google.com/storage/docs/json_api/v1/projects/hmacKeys/update#request-body) for valid states.

  ## Parameters

  *   `project_id` (*type:* `String.t()`) - Project ID owning the service account of the updated key.
  *   `access_id` (*type:* `String.t()`) - Name of the HMAC key being updated.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request.
      *   `body` (*type:* `Googly.CloudStorage.Model.HmacKeyMetadata.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.HmacKeyMetadata{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec update(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.HmacKeyMetadata.t()} | {:error, term()}
  def update(project_id, access_id, opts \\ []) do
    Request.run(
      method: :put,
      url: "/storage/v1/projects/{projectId}/hmacKeys/{accessId}",
      path_params: %{
        "projectId" => URI.encode(project_id, &URI.char_unreserved?/1),
        "accessId" => URI.encode(access_id, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.HmacKeyMetadata,
      opts: opts
    )
  end
end
