# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Projects.Locations.Processors.ProcessorVersions.Evaluations do
  @moduledoc """
  Endpoints for the `Projects.Locations.Processors.ProcessorVersions.Evaluations` resource.
  """

  alias Googly.DocumentAI.Request

  @doc """
  Retrieves a specific evaluation.

  ## Parameters

  *   `name` (*type:* `String.t()`) - Required. The resource name of the Evaluation to get. `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}/evaluations/{evaluation}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Evaluation{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec get(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Evaluation.t()} | {:error, term()}
  def get(name, opts \\ []) do
    Request.run(
      method: :get,
      url: "/v1/{+name}",
      path_params: %{"name" => URI.encode(name, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"}
      },
      decode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1Evaluation,
      opts: opts
    )
  end

  @doc """
  Retrieves a set of evaluations for a given processor version.

  ## Parameters

  *   `parent` (*type:* `String.t()`) - Required. The resource name of the ProcessorVersion to list evaluations for. `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.
      *   `page_size` (*type:* `integer()`) - The standard list page size. If unspecified, at most `5` evaluations are returned. The maximum value is `100`. Values above `100` are coerced to `100`.
      *   `page_token` (*type:* `String.t()`) - A page token, received from a previous `ListEvaluations` call. Provide this to retrieve the subsequent page.

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListEvaluationsResponse{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec list(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListEvaluationsResponse.t()}
          | {:error, term()}
  def list(parent, opts \\ []) do
    Request.run(
      method: :get,
      url: "/v1/{+parent}/evaluations",
      path_params: %{"parent" => URI.encode(parent, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"},
        page_size: {:query, "pageSize"},
        page_token: {:query, "pageToken"}
      },
      decode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListEvaluationsResponse,
      opts: opts
    )
  end
end
