# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.DefaultObjectAccessControls do
  @moduledoc """
  Endpoints for the `DefaultObjectAccessControls` resource.
  """

  alias Googly.CloudStorage.Request

  @doc """
  Permanently deletes the default object ACL entry for the specified entity on the specified bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of a bucket.
  *   `entity` (*type:* `String.t()`) - The entity holding the permission. Can be user-userId, user-emailAddress, group-groupId, group-emailAddress, allUsers, or allAuthenticatedUsers.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, Req.Response.t()}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec delete(String.t(), String.t(), keyword()) :: {:ok, Req.Response.t()} | {:error, term()}
  def delete(bucket, entity, opts \\ []) do
    Request.run(
      method: :delete,
      url: "/storage/v1/b/{bucket}/defaultObjectAcl/{entity}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "entity" => URI.encode(entity, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"}
      },
      decode: nil,
      opts: opts
    )
  end

  @doc """
  Returns the default object ACL entry for the specified entity on the specified bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of a bucket.
  *   `entity` (*type:* `String.t()`) - The entity holding the permission. Can be user-userId, user-emailAddress, group-groupId, group-emailAddress, allUsers, or allAuthenticatedUsers.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.ObjectAccessControl{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec get(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.ObjectAccessControl.t()} | {:error, term()}
  def get(bucket, entity, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/b/{bucket}/defaultObjectAcl/{entity}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "entity" => URI.encode(entity, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.ObjectAccessControl,
      opts: opts
    )
  end

  @doc """
  Creates a new default object ACL entry on the specified bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of a bucket.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.ObjectAccessControl.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.ObjectAccessControl{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec insert(String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.ObjectAccessControl.t()} | {:error, term()}
  def insert(bucket, opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/b/{bucket}/defaultObjectAcl",
      path_params: %{"bucket" => URI.encode(bucket, &URI.char_unreserved?/1)},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.ObjectAccessControl,
      opts: opts
    )
  end

  @doc """
  Retrieves default object ACL entries on the specified bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of a bucket.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `if_metageneration_match` (*type:* `String.t()`) - If present, only return default ACL listing if the bucket's current metageneration matches this value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - If present, only return default ACL listing if the bucket's current metageneration does not match the given value.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.ObjectAccessControls{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec list(String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.ObjectAccessControls.t()} | {:error, term()}
  def list(bucket, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/b/{bucket}/defaultObjectAcl",
      path_params: %{"bucket" => URI.encode(bucket, &URI.char_unreserved?/1)},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.ObjectAccessControls,
      opts: opts
    )
  end

  @doc """
  Patches a default object ACL entry on the specified bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of a bucket.
  *   `entity` (*type:* `String.t()`) - The entity holding the permission. Can be user-userId, user-emailAddress, group-groupId, group-emailAddress, allUsers, or allAuthenticatedUsers.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.ObjectAccessControl.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.ObjectAccessControl{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec patch(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.ObjectAccessControl.t()} | {:error, term()}
  def patch(bucket, entity, opts \\ []) do
    Request.run(
      method: :patch,
      url: "/storage/v1/b/{bucket}/defaultObjectAcl/{entity}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "entity" => URI.encode(entity, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.ObjectAccessControl,
      opts: opts
    )
  end

  @doc """
  Updates a default object ACL entry on the specified bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of a bucket.
  *   `entity` (*type:* `String.t()`) - The entity holding the permission. Can be user-userId, user-emailAddress, group-groupId, group-emailAddress, allUsers, or allAuthenticatedUsers.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.ObjectAccessControl.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.ObjectAccessControl{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec update(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.ObjectAccessControl.t()} | {:error, term()}
  def update(bucket, entity, opts \\ []) do
    Request.run(
      method: :put,
      url: "/storage/v1/b/{bucket}/defaultObjectAcl/{entity}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "entity" => URI.encode(entity, &(URI.char_unreserved?(&1) or &1 == ?/))
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.ObjectAccessControl,
      opts: opts
    )
  end
end
