# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.CloudStorage.Objects do
  @moduledoc """
  Endpoints for the `Objects` resource.
  """

  alias Googly.CloudStorage.Request

  @doc """
  Initiates a long-running bulk restore operation on the specified bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `body` (*type:* `Googly.CloudStorage.Model.BulkRestoreObjectsRequest.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.GoogleLongrunningOperation{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec bulk_restore(String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.GoogleLongrunningOperation.t()} | {:error, term()}
  def bulk_restore(bucket, opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/b/{bucket}/o/bulkRestore",
      path_params: %{"bucket" => URI.encode(bucket, &URI.char_unreserved?/1)},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.GoogleLongrunningOperation,
      opts: opts
    )
  end

  @doc """
  Concatenates a list of existing objects into a new object in the same bucket.

  ## Parameters

  *   `destination_bucket` (*type:* `String.t()`) - Name of the bucket containing the source objects. The destination object is stored in this bucket.
  *   `destination_object` (*type:* `String.t()`) - Name of the new object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `destination_predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to the destination object.
      *   `drop_context_groups` (*type:* `list(String.t())`) - Specifies which groups of Object Contexts from the source object(s) should be dropped from the destination object.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `kms_key_name` (*type:* `String.t()`) - Resource name of the Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key, that will be used to encrypt the object. Overrides the object metadata's kms_key_name value, if any.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.ComposeRequest.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec compose(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def compose(destination_bucket, destination_object, opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/b/{destinationBucket}/o/{destinationObject}/compose",
      path_params: %{
        "destinationBucket" => URI.encode(destination_bucket, &URI.char_unreserved?/1),
        "destinationObject" => URI.encode(destination_object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        destination_predefined_acl: {:query, "destinationPredefinedAcl"},
        drop_context_groups: {:query, "dropContextGroups"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        kms_key_name: {:query, "kmsKeyName"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Copies a source object to a destination object. Optionally overrides metadata.

  ## Parameters

  *   `source_bucket` (*type:* `String.t()`) - Name of the bucket in which to find the source object.
  *   `source_object` (*type:* `String.t()`) - Name of the source object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `destination_bucket` (*type:* `String.t()`) - Name of the bucket in which to store the new object. Overrides the provided object metadata's bucket value, if any.For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `destination_object` (*type:* `String.t()`) - Name of the new object. Required when the object metadata is not otherwise provided. Overrides the object metadata's name value, if any.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `destination_kms_key_name` (*type:* `String.t()`) - Resource name of the Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key, that will be used to encrypt the object. Overrides the object metadata's kms_key_name value, if any.
      *   `destination_predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to the destination object.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current metageneration does not match the given value.
      *   `if_source_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current generation matches the given value.
      *   `if_source_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current generation does not match the given value.
      *   `if_source_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current metageneration matches the given value.
      *   `if_source_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current metageneration does not match the given value.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl, unless the object resource specifies the acl property, when it defaults to full.
      *   `source_generation` (*type:* `String.t()`) - If present, selects a specific revision of the source object (as opposed to the latest version, the default).
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.Object.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec copy(String.t(), String.t(), String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def copy(source_bucket, source_object, destination_bucket, destination_object, opts \\ []) do
    Request.run(
      method: :post,
      url:
        "/storage/v1/b/{sourceBucket}/o/{sourceObject}/copyTo/b/{destinationBucket}/o/{destinationObject}",
      path_params: %{
        "sourceBucket" => URI.encode(source_bucket, &URI.char_unreserved?/1),
        "sourceObject" => URI.encode(source_object, &URI.char_unreserved?/1),
        "destinationBucket" => URI.encode(destination_bucket, &URI.char_unreserved?/1),
        "destinationObject" => URI.encode(destination_object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        destination_kms_key_name: {:query, "destinationKmsKeyName"},
        destination_predefined_acl: {:query, "destinationPredefinedAcl"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        if_source_generation_match: {:query, "ifSourceGenerationMatch"},
        if_source_generation_not_match: {:query, "ifSourceGenerationNotMatch"},
        if_source_metageneration_match: {:query, "ifSourceMetagenerationMatch"},
        if_source_metageneration_not_match: {:query, "ifSourceMetagenerationNotMatch"},
        projection: {:query, "projection"},
        source_generation: {:query, "sourceGeneration"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Deletes an object and its metadata. Deletions are permanent if versioning is not enabled for the bucket, or if the generation parameter is used.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `generation` (*type:* `String.t()`) - If present, permanently deletes a specific revision of this object (as opposed to the latest version, the default).
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration does not match the given value.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, Req.Response.t()}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec delete(String.t(), String.t(), keyword()) :: {:ok, Req.Response.t()} | {:error, term()}
  def delete(bucket, object, opts \\ []) do
    Request.run(
      method: :delete,
      url: "/storage/v1/b/{bucket}/o/{object}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        generation: {:query, "generation"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        user_project: {:query, "userProject"}
      },
      decode: nil,
      opts: opts
    )
  end

  @doc """
  Retrieves an object or its metadata.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `generation` (*type:* `String.t()`) - If present, selects a specific revision of this object (as opposed to the latest version, the default).
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration does not match the given value.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl.
      *   `restore_token` (*type:* `String.t()`) - Restore token used to differentiate soft-deleted objects with the same name and generation. Only applicable for hierarchical namespace buckets and if softDeleted is set to true. This parameter is optional, and is only required in the rare case when there are multiple soft-deleted objects with the same name and generation.
      *   `soft_deleted` (*type:* `boolean()`) - If true, only soft-deleted object versions will be listed. The default is false. For more information, see [Soft Delete](https://cloud.google.com/storage/docs/soft-delete).
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec get(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def get(bucket, object, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/b/{bucket}/o/{object}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        generation: {:query, "generation"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        projection: {:query, "projection"},
        restore_token: {:query, "restoreToken"},
        soft_deleted: {:query, "softDeleted"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Returns an IAM policy for the specified object.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `generation` (*type:* `String.t()`) - If present, selects a specific revision of this object (as opposed to the latest version, the default).
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Policy{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec get_iam_policy(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Policy.t()} | {:error, term()}
  def get_iam_policy(bucket, object, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/b/{bucket}/o/{object}/iam",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        generation: {:query, "generation"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.Policy,
      opts: opts
    )
  end

  @doc """
  Stores a new object and metadata.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which to store the new object. Overrides the provided object metadata's bucket value, if any.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `content_encoding` (*type:* `String.t()`) - If set, sets the contentEncoding property of the final object to this value. Setting this parameter is equivalent to setting the contentEncoding metadata property. This can be useful when uploading an object with uploadType=media to indicate the encoding of the content being uploaded.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration does not match the given value.
      *   `kms_key_name` (*type:* `String.t()`) - Resource name of the Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key, that will be used to encrypt the object. Overrides the object metadata's kms_key_name value, if any.
      *   `name` (*type:* `String.t()`) - Name of the object. Required when the object metadata is not otherwise provided. Overrides the object metadata's name value, if any. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
      *   `predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to this object.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl, unless the object resource specifies the acl property, when it defaults to full.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.Object.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec insert(String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def insert(bucket, opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/b/{bucket}/o",
      path_params: %{"bucket" => URI.encode(bucket, &URI.char_unreserved?/1)},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        content_encoding: {:query, "contentEncoding"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        kms_key_name: {:query, "kmsKeyName"},
        name: {:query, "name"},
        predefined_acl: {:query, "predefinedAcl"},
        projection: {:query, "projection"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Stores a new object and metadata.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which to store the new object. Overrides the provided object metadata's bucket value, if any.
  *   `data` (*type:* `iodata() | File.Stream.t()`) - Content to upload: iodata, or a `File.Stream` (e.g. `File.stream!(path)`) to stream it from disk with a computed content-length.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `content_encoding` (*type:* `String.t()`) - If set, sets the contentEncoding property of the final object to this value. Setting this parameter is equivalent to setting the contentEncoding metadata property. This can be useful when uploading an object with uploadType=media to indicate the encoding of the content being uploaded.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration does not match the given value.
      *   `kms_key_name` (*type:* `String.t()`) - Resource name of the Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key, that will be used to encrypt the object. Overrides the object metadata's kms_key_name value, if any.
      *   `name` (*type:* `String.t()`) - Name of the object. Required when the object metadata is not otherwise provided. Overrides the object metadata's name value, if any. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
      *   `predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to this object.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl, unless the object resource specifies the acl property, when it defaults to full.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec insert_media(String.t(), iodata() | File.Stream.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def insert_media(bucket, data, opts \\ []) do
    Request.upload(
      method: :post,
      url: "/upload/storage/v1/b/{bucket}/o",
      path_params: %{"bucket" => URI.encode(bucket, &URI.char_unreserved?/1)},
      upload_type: "media",
      data: data,
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        content_encoding: {:query, "contentEncoding"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        kms_key_name: {:query, "kmsKeyName"},
        name: {:query, "name"},
        predefined_acl: {:query, "predefinedAcl"},
        projection: {:query, "projection"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Stores a new object and metadata.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which to store the new object. Overrides the provided object metadata's bucket value, if any.
  *   `metadata` (*type:* `Googly.CloudStorage.Model.Object.t()`) - Resource metadata to store alongside the content.
  *   `data` (*type:* `iodata() | File.Stream.t()`) - Content to upload: iodata, or a `File.Stream` (e.g. `File.stream!(path)`) to stream it from disk with a computed content-length.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `content_encoding` (*type:* `String.t()`) - If set, sets the contentEncoding property of the final object to this value. Setting this parameter is equivalent to setting the contentEncoding metadata property. This can be useful when uploading an object with uploadType=media to indicate the encoding of the content being uploaded.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration does not match the given value.
      *   `kms_key_name` (*type:* `String.t()`) - Resource name of the Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key, that will be used to encrypt the object. Overrides the object metadata's kms_key_name value, if any.
      *   `name` (*type:* `String.t()`) - Name of the object. Required when the object metadata is not otherwise provided. Overrides the object metadata's name value, if any. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
      *   `predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to this object.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl, unless the object resource specifies the acl property, when it defaults to full.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec insert_multipart(
          String.t(),
          Googly.CloudStorage.Model.Object.t(),
          iodata() | File.Stream.t(),
          keyword()
        ) :: {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def insert_multipart(bucket, metadata, data, opts \\ []) do
    Request.upload(
      method: :post,
      url: "/upload/storage/v1/b/{bucket}/o",
      path_params: %{"bucket" => URI.encode(bucket, &URI.char_unreserved?/1)},
      upload_type: "multipart",
      metadata: metadata,
      data: data,
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        content_encoding: {:query, "contentEncoding"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        kms_key_name: {:query, "kmsKeyName"},
        name: {:query, "name"},
        predefined_acl: {:query, "predefinedAcl"},
        projection: {:query, "projection"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Retrieves a list of objects matching the criteria.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which to look for objects.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `delimiter` (*type:* `String.t()`) - Returns results in a directory-like mode. items will contain only objects whose names, aside from the prefix, do not contain delimiter. Objects whose names, aside from the prefix, contain delimiter will have their name, truncated after the delimiter, returned in prefixes. Duplicate prefixes are omitted.
      *   `end_offset` (*type:* `String.t()`) - Filter results to objects whose names are lexicographically before endOffset. If startOffset is also set, the objects listed will have names between startOffset (inclusive) and endOffset (exclusive).
      *   `filter` (*type:* `String.t()`) - Filter the returned objects. Currently only supported for the contexts field. If delimiter is set, the returned prefixes are exempt from this filter.
      *   `include_folders_as_prefixes` (*type:* `boolean()`) - Only applicable if delimiter is set to '/'. If true, will also include folders and managed folders (besides objects) in the returned prefixes.
      *   `include_trailing_delimiter` (*type:* `boolean()`) - If true, objects that end in exactly one instance of delimiter will have their metadata included in items in addition to prefixes.
      *   `match_glob` (*type:* `String.t()`) - Filter results to objects and prefixes that match this glob pattern.
      *   `max_results` (*type:* `integer()`) - Maximum number of items plus prefixes to return in a single page of responses. As duplicate prefixes are omitted, fewer total results may be returned than requested. The service will use this parameter or 1,000 items, whichever is smaller.
      *   `page_token` (*type:* `String.t()`) - A previously-returned page token representing part of the larger set of results to view.
      *   `prefix` (*type:* `String.t()`) - Filter results to objects whose names begin with this prefix.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl.
      *   `soft_deleted` (*type:* `boolean()`) - If true, only soft-deleted object versions will be listed. The default is false. For more information, see [Soft Delete](https://cloud.google.com/storage/docs/soft-delete).
      *   `start_offset` (*type:* `String.t()`) - Filter results to objects whose names are lexicographically equal to or after startOffset. If endOffset is also set, the objects listed will have names between startOffset (inclusive) and endOffset (exclusive).
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `versions` (*type:* `boolean()`) - If true, lists all versions of an object as distinct results. The default is false. For more information, see [Object Versioning](https://cloud.google.com/storage/docs/object-versioning).

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Objects{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec list(String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Objects.t()} | {:error, term()}
  def list(bucket, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/b/{bucket}/o",
      path_params: %{"bucket" => URI.encode(bucket, &URI.char_unreserved?/1)},
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        delimiter: {:query, "delimiter"},
        end_offset: {:query, "endOffset"},
        filter: {:query, "filter"},
        include_folders_as_prefixes: {:query, "includeFoldersAsPrefixes"},
        include_trailing_delimiter: {:query, "includeTrailingDelimiter"},
        match_glob: {:query, "matchGlob"},
        max_results: {:query, "maxResults"},
        page_token: {:query, "pageToken"},
        prefix: {:query, "prefix"},
        projection: {:query, "projection"},
        soft_deleted: {:query, "softDeleted"},
        start_offset: {:query, "startOffset"},
        user_project: {:query, "userProject"},
        versions: {:query, "versions"}
      },
      decode: Googly.CloudStorage.Model.Objects,
      opts: opts
    )
  end

  @doc """
  Moves the source object to the destination object in the same bucket.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `source_object` (*type:* `String.t()`) - Name of the source object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `destination_object` (*type:* `String.t()`) - Name of the destination object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object. `ifGenerationMatch` and `ifGenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.`ifGenerationMatch` and `ifGenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current metageneration matches the given value. `ifMetagenerationMatch` and `ifMetagenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current metageneration does not match the given value. `ifMetagenerationMatch` and `ifMetagenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `if_source_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current generation matches the given value. `ifSourceGenerationMatch` and `ifSourceGenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `if_source_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current generation does not match the given value. `ifSourceGenerationMatch` and `ifSourceGenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `if_source_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current metageneration matches the given value. `ifSourceMetagenerationMatch` and `ifSourceMetagenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `if_source_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current metageneration does not match the given value. `ifSourceMetagenerationMatch` and `ifSourceMetagenerationNotMatch` conditions are mutually exclusive: it's an error for both of them to be set in the request.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec move(String.t(), String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def move(bucket, source_object, destination_object, opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/b/{bucket}/o/{sourceObject}/moveTo/o/{destinationObject}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "sourceObject" => URI.encode(source_object, &URI.char_unreserved?/1),
        "destinationObject" => URI.encode(destination_object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        if_source_generation_match: {:query, "ifSourceGenerationMatch"},
        if_source_generation_not_match: {:query, "ifSourceGenerationNotMatch"},
        if_source_metageneration_match: {:query, "ifSourceMetagenerationMatch"},
        if_source_metageneration_not_match: {:query, "ifSourceMetagenerationNotMatch"},
        projection: {:query, "projection"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Patches an object's metadata.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `generation` (*type:* `String.t()`) - If present, selects a specific revision of this object (as opposed to the latest version, the default).
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration does not match the given value.
      *   `override_unlocked_retention` (*type:* `boolean()`) - Must be true to remove the retention configuration, reduce its unlocked retention period, or change its mode from unlocked to locked.
      *   `predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to this object.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to full.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request, for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.Object.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec patch(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def patch(bucket, object, opts \\ []) do
    Request.run(
      method: :patch,
      url: "/storage/v1/b/{bucket}/o/{object}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        generation: {:query, "generation"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        override_unlocked_retention: {:query, "overrideUnlockedRetention"},
        predefined_acl: {:query, "predefinedAcl"},
        projection: {:query, "projection"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Restores a soft-deleted object.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `generation` (*type:* `String.t()`) - Selects a specific revision of this object.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `copy_source_acl` (*type:* `boolean()`) - If true, copies the source object's ACL; otherwise, uses the bucket's default object ACL. The default is false.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's one live generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether none of the object's live generations match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's one live metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether none of the object's live metagenerations match the given value.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to full.
      *   `restore_token` (*type:* `String.t()`) - Restore token used to differentiate sof-deleted objects with the same name and generation. Only applicable for hierarchical namespace buckets. This parameter is optional, and is only required in the rare case when there are multiple soft-deleted objects with the same name and generation.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec restore(String.t(), String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def restore(bucket, object, generation, opts \\ []) do
    Request.run(
      method: :post,
      url: "/storage/v1/b/{bucket}/o/{object}/restore",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [{"generation", generation}],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        copy_source_acl: {:query, "copySourceAcl"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        projection: {:query, "projection"},
        restore_token: {:query, "restoreToken"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end

  @doc """
  Rewrites a source object to a destination object. Optionally overrides metadata.

  ## Parameters

  *   `source_bucket` (*type:* `String.t()`) - Name of the bucket in which to find the source object.
  *   `source_object` (*type:* `String.t()`) - Name of the source object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `destination_bucket` (*type:* `String.t()`) - Name of the bucket in which to store the new object. Overrides the provided object metadata's bucket value, if any.
  *   `destination_object` (*type:* `String.t()`) - Name of the new object. Required when the object metadata is not otherwise provided. Overrides the object metadata's name value, if any. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `destination_kms_key_name` (*type:* `String.t()`) - Resource name of the Cloud KMS key, of the form projects/my-project/locations/global/keyRings/my-kr/cryptoKeys/my-key, that will be used to encrypt the object. Overrides the object metadata's kms_key_name value, if any.
      *   `destination_predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to the destination object.
      *   `drop_context_groups` (*type:* `list(String.t())`) - Specifies which groups of Object Contexts from the source object should be dropped from the destination object.
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the destination object's current metageneration does not match the given value.
      *   `if_source_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current generation matches the given value.
      *   `if_source_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current generation does not match the given value.
      *   `if_source_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current metageneration matches the given value.
      *   `if_source_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the source object's current metageneration does not match the given value.
      *   `max_bytes_rewritten_per_call` (*type:* `String.t()`) - The maximum number of bytes that will be rewritten per rewrite request. Most callers shouldn't need to specify this parameter - it is primarily in place to support testing. If specified the value must be an integral multiple of 1 MiB (1048576). Also, this only applies to requests where the source and destination span locations and/or storage classes. Finally, this value must not change across rewrite calls else you'll get an error that the rewriteToken is invalid.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to noAcl, unless the object resource specifies the acl property, when it defaults to full.
      *   `rewrite_token` (*type:* `String.t()`) - Include this field (from the previous rewrite response) on each rewrite request after the first one, until the rewrite response 'done' flag is true. Calls that provide a rewriteToken can omit all other request fields, but if included those fields must match the values provided in the first rewrite request.
      *   `source_generation` (*type:* `String.t()`) - If present, selects a specific revision of the source object (as opposed to the latest version, the default).
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.Object.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.RewriteResponse{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec rewrite(String.t(), String.t(), String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.RewriteResponse.t()} | {:error, term()}
  def rewrite(source_bucket, source_object, destination_bucket, destination_object, opts \\ []) do
    Request.run(
      method: :post,
      url:
        "/storage/v1/b/{sourceBucket}/o/{sourceObject}/rewriteTo/b/{destinationBucket}/o/{destinationObject}",
      path_params: %{
        "sourceBucket" => URI.encode(source_bucket, &URI.char_unreserved?/1),
        "sourceObject" => URI.encode(source_object, &URI.char_unreserved?/1),
        "destinationBucket" => URI.encode(destination_bucket, &URI.char_unreserved?/1),
        "destinationObject" => URI.encode(destination_object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        destination_kms_key_name: {:query, "destinationKmsKeyName"},
        destination_predefined_acl: {:query, "destinationPredefinedAcl"},
        drop_context_groups: {:query, "dropContextGroups"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        if_source_generation_match: {:query, "ifSourceGenerationMatch"},
        if_source_generation_not_match: {:query, "ifSourceGenerationNotMatch"},
        if_source_metageneration_match: {:query, "ifSourceMetagenerationMatch"},
        if_source_metageneration_not_match: {:query, "ifSourceMetagenerationNotMatch"},
        max_bytes_rewritten_per_call: {:query, "maxBytesRewrittenPerCall"},
        projection: {:query, "projection"},
        rewrite_token: {:query, "rewriteToken"},
        source_generation: {:query, "sourceGeneration"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.RewriteResponse,
      opts: opts
    )
  end

  @doc """
  Updates an IAM policy for the specified object.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `generation` (*type:* `String.t()`) - If present, selects a specific revision of this object (as opposed to the latest version, the default).
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.Policy.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Policy{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec set_iam_policy(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Policy.t()} | {:error, term()}
  def set_iam_policy(bucket, object, opts \\ []) do
    Request.run(
      method: :put,
      url: "/storage/v1/b/{bucket}/o/{object}/iam",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        generation: {:query, "generation"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.Policy,
      opts: opts
    )
  end

  @doc """
  Tests a set of permissions on the given object to see which, if any, are held by the caller.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `permissions` (*type:* `list(String.t())`) - Permissions to test.
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `generation` (*type:* `String.t()`) - If present, selects a specific revision of this object (as opposed to the latest version, the default).
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.TestIamPermissionsResponse{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec test_iam_permissions(String.t(), String.t(), list(String.t()), keyword()) ::
          {:ok, Googly.CloudStorage.Model.TestIamPermissionsResponse.t()} | {:error, term()}
  def test_iam_permissions(bucket, object, permissions, opts \\ []) do
    Request.run(
      method: :get,
      url: "/storage/v1/b/{bucket}/o/{object}/iam/testPermissions",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [{"permissions", permissions}],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        generation: {:query, "generation"},
        user_project: {:query, "userProject"}
      },
      decode: Googly.CloudStorage.Model.TestIamPermissionsResponse,
      opts: opts
    )
  end

  @doc """
  Updates an object's metadata.

  ## Parameters

  *   `bucket` (*type:* `String.t()`) - Name of the bucket in which the object resides.
  *   `object` (*type:* `String.t()`) - Name of the object. For information about how to URL encode object names to be path safe, see [Encoding URI Path Parts](https://cloud.google.com/storage/docs/request-endpoints#encoding).
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `alt` (*type:* `String.t()`) - Data format for the response.
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      *   `upload_type` (*type:* `String.t()`) - Upload protocol for media (e.g. "media", "multipart", "resumable").
      *   `user_ip` (*type:* `String.t()`) - Deprecated. Please use quotaUser instead.
      *   `generation` (*type:* `String.t()`) - If present, selects a specific revision of this object (as opposed to the latest version, the default).
      *   `if_generation_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation matches the given value. Setting to 0 makes the operation succeed only if there are no live versions of the object.
      *   `if_generation_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current generation does not match the given value. If no live object exists, the precondition fails. Setting to 0 makes the operation succeed only if there is a live version of the object.
      *   `if_metageneration_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration matches the given value.
      *   `if_metageneration_not_match` (*type:* `String.t()`) - Makes the operation conditional on whether the object's current metageneration does not match the given value.
      *   `override_unlocked_retention` (*type:* `boolean()`) - Must be true to remove the retention configuration, reduce its unlocked retention period, or change its mode from unlocked to locked.
      *   `predefined_acl` (*type:* `String.t()`) - Apply a predefined set of access controls to this object.
      *   `projection` (*type:* `String.t()`) - Set of properties to return. Defaults to full.
      *   `user_project` (*type:* `String.t()`) - The project to be billed for this request. Required for Requester Pays buckets.
      *   `body` (*type:* `Googly.CloudStorage.Model.Object.t()`) - 

  ## Returns

  *   `{:ok, %Googly.CloudStorage.Model.Object{}}` on success
  *   `{:error, %Googly.CloudStorage.Error{}}` on failure
  """
  @spec update(String.t(), String.t(), keyword()) ::
          {:ok, Googly.CloudStorage.Model.Object.t()} | {:error, term()}
  def update(bucket, object, opts \\ []) do
    Request.run(
      method: :put,
      url: "/storage/v1/b/{bucket}/o/{object}",
      path_params: %{
        "bucket" => URI.encode(bucket, &URI.char_unreserved?/1),
        "object" => URI.encode(object, &URI.char_unreserved?/1)
      },
      query: [],
      params: %{
        alt: {:query, "alt"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_type: {:query, "uploadType"},
        user_ip: {:query, "userIp"},
        generation: {:query, "generation"},
        if_generation_match: {:query, "ifGenerationMatch"},
        if_generation_not_match: {:query, "ifGenerationNotMatch"},
        if_metageneration_match: {:query, "ifMetagenerationMatch"},
        if_metageneration_not_match: {:query, "ifMetagenerationNotMatch"},
        override_unlocked_retention: {:query, "overrideUnlockedRetention"},
        predefined_acl: {:query, "predefinedAcl"},
        projection: {:query, "projection"},
        user_project: {:query, "userProject"},
        body: {:body, nil}
      },
      decode: Googly.CloudStorage.Model.Object,
      opts: opts
    )
  end
end
