# NOTE: This file is auto generated by googly. Do not edit it manually.

defmodule Googly.DocumentAI.Projects.Locations.Schemas.SchemaVersions do
  @moduledoc """
  Endpoints for the `Projects.Locations.Schemas.SchemaVersions` resource.
  """

  alias Googly.DocumentAI.Request

  @doc """
  Creates a schema version.

  ## Parameters

  *   `parent` (*type:* `String.t()`) - Required. The parent (project and location) under which to create the SchemaVersion. Format: `projects/{project}/locations/{location}/schemas/{schema}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.
      *   `body` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.t()`) - 

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec create(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.t()}
          | {:error, term()}
  def create(parent, opts \\ []) do
    Request.run(
      method: :post,
      url: "/v1/{+parent}/schemaVersions",
      path_params: %{"parent" => URI.encode(parent, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"},
        body: {:body, nil}
      },
      decode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion,
      opts: opts
    )
  end

  @doc """
  Deletes a schema version.

  ## Parameters

  *   `name` (*type:* `String.t()`) - Required. The name of the SchemaVersion to delete. Format: `projects/{project}/locations/{location}/schemas/{schema}/schemaVersions/{schema_version}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleLongrunningOperation{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec delete(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleLongrunningOperation.t()} | {:error, term()}
  def delete(name, opts \\ []) do
    Request.run(
      method: :delete,
      url: "/v1/{+name}",
      path_params: %{"name" => URI.encode(name, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"}
      },
      decode: Googly.DocumentAI.Model.GoogleLongrunningOperation,
      opts: opts
    )
  end

  @doc """
  Generates a schema version.

  ## Parameters

  *   `parent` (*type:* `String.t()`) - Required. The parent (project, location and schema) under which to generate the SchemaVersion. Format: `projects/{project}/locations/{location}/schemas/{schema}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.
      *   `body` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionRequest.t()`) - 

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionResponse{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec generate(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionResponse.t()}
          | {:error, term()}
  def generate(parent, opts \\ []) do
    Request.run(
      method: :post,
      url: "/v1/{+parent}/schemaVersions:generate",
      path_params: %{"parent" => URI.encode(parent, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"},
        body: {:body, nil}
      },
      decode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1GenerateSchemaVersionResponse,
      opts: opts
    )
  end

  @doc """
  Gets a schema version.

  ## Parameters

  *   `name` (*type:* `String.t()`) - Required. The name of the SchemaVersion to get. Format: `projects/{project}/locations/{location}/schemas/{schema}/schemaVersions/{schema_version}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec get(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.t()}
          | {:error, term()}
  def get(name, opts \\ []) do
    Request.run(
      method: :get,
      url: "/v1/{+name}",
      path_params: %{"name" => URI.encode(name, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"}
      },
      decode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion,
      opts: opts
    )
  end

  @doc """
  Lists SchemaVersions.

  ## Parameters

  *   `parent` (*type:* `String.t()`) - Required. Format: `projects/{project}/locations/{location}/schemas/{schema}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.
      *   `page_size` (*type:* `integer()`) - Optional. The maximum number of SchemaVersion to return. If unspecified, at most `10` SchemaVersion will be returned. The maximum value is `20`. Values above `20` will be coerced to `20`.
      *   `page_token` (*type:* `String.t()`) - Optional. Returns the SchemaVersion sorted by creation time. The page token will point to the next SchemaVersion.

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListSchemaVersionsResponse{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec list(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListSchemaVersionsResponse.t()}
          | {:error, term()}
  def list(parent, opts \\ []) do
    Request.run(
      method: :get,
      url: "/v1/{+parent}/schemaVersions",
      path_params: %{"parent" => URI.encode(parent, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"},
        page_size: {:query, "pageSize"},
        page_token: {:query, "pageToken"}
      },
      decode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1ListSchemaVersionsResponse,
      opts: opts
    )
  end

  @doc """
  Updates a schema version. Editable fields are: - `display_name` - `labels`

  ## Parameters

  *   `name` (*type:* `String.t()`) - Identifier. The resource name of the SchemaVersion. Format: `projects/{project}/locations/{location}/schemas/{schema}/schemaVersions/{schema_version}`
  *   `opts` (*type:* `keyword()`) - Query and call options (`:token`, plus any of the below)
      *   `access_token` (*type:* `String.t()`) - OAuth access token.
      *   `alt` (*type:* `String.t()`) - Data format for response.
      *   `callback` (*type:* `String.t()`) - JSONP
      *   `fields` (*type:* `String.t()`) - Selector specifying which fields to include in a partial response.
      *   `key` (*type:* `String.t()`) - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      *   `oauth_token` (*type:* `String.t()`) - OAuth 2.0 token for the current user.
      *   `pretty_print` (*type:* `boolean()`) - Returns response with indentations and line breaks.
      *   `quota_user` (*type:* `String.t()`) - Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      *   `upload_protocol` (*type:* `String.t()`) - Upload protocol for media (e.g. "raw", "multipart").
      *   `upload_type` (*type:* `String.t()`) - Legacy upload protocol for media (e.g. "media", "multipart").
      *   `xgafv` (*type:* `String.t()`) - V1 error format.
      *   `update_mask` (*type:* `String.t()`) - Optional. The update mask to apply to the resource. **Note:** Only the following fields can be updated: - `display_name` - `labels`
      *   `body` (*type:* `Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.t()`) - 

  ## Returns

  *   `{:ok, %Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion{}}` on success
  *   `{:error, %Googly.DocumentAI.Error{}}` on failure
  """
  @spec patch(String.t(), keyword()) ::
          {:ok, Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion.t()}
          | {:error, term()}
  def patch(name, opts \\ []) do
    Request.run(
      method: :patch,
      url: "/v1/{+name}",
      path_params: %{"name" => URI.encode(name, &(URI.char_unreserved?(&1) or &1 == ?/))},
      query: [],
      params: %{
        access_token: {:query, "access_token"},
        alt: {:query, "alt"},
        callback: {:query, "callback"},
        fields: {:query, "fields"},
        key: {:query, "key"},
        oauth_token: {:query, "oauth_token"},
        pretty_print: {:query, "prettyPrint"},
        quota_user: {:query, "quotaUser"},
        upload_protocol: {:query, "upload_protocol"},
        upload_type: {:query, "uploadType"},
        xgafv: {:query, "$.xgafv"},
        update_mask: {:query, "updateMask"},
        body: {:body, nil}
      },
      decode: Googly.DocumentAI.Model.GoogleCloudDocumentaiV1SchemaVersion,
      opts: opts
    )
  end
end
